# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gr4vy < Formula
  desc "The Gr4vy command-line interface"
  homepage "https://github.com/gr4vy/gr4vy-cli"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gr4vy/gr4vy-cli/releases/download/v1.2.0/gr4vy_1.2.0_darwin_amd64.tar.gz"
      sha256 "c54f9bfdae3763bd1ca6c5cc69c299d2d5de3c97ad81392cb5641bcd441c015a"

      define_method(:install) do
        bin.install "gr4vy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gr4vy/gr4vy-cli/releases/download/v1.2.0/gr4vy_1.2.0_darwin_arm64.tar.gz"
      sha256 "979b478b693829b0f60cf16fbce08c9b0614a76852d4738f8509787944e84ff8"

      define_method(:install) do
        bin.install "gr4vy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gr4vy/gr4vy-cli/releases/download/v1.2.0/gr4vy_1.2.0_linux_amd64.tar.gz"
      sha256 "61a497bf5b6e87fba73d7a0308bea78970c606d0b0d1bb3988c9c94c736e1530"
      define_method(:install) do
        bin.install "gr4vy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gr4vy/gr4vy-cli/releases/download/v1.2.0/gr4vy_1.2.0_linux_arm64.tar.gz"
      sha256 "5dae424d46c99d41f48ce607773d653517bff5d050670f3ddec12c0b6671dd78"
      define_method(:install) do
        bin.install "gr4vy"
      end
    end
  end

  test do
    system "#{bin}/gr4vy version"
  end
end
